/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author walksydn
 */
public class OppsFrame extends javax.swing.JFrame {

    /**
     * Creates new form OppsFrame
     */
    public OppsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deltaIntLBL = new javax.swing.JLabel();
        intLBL = new javax.swing.JLabel();
        doubleLBL = new javax.swing.JLabel();
        deltaDoubleLBL = new javax.swing.JLabel();
        deltaDoubleTF = new javax.swing.JTextField();
        intTF = new javax.swing.JTextField();
        doubleTF = new javax.swing.JTextField();
        deltaIntTF = new javax.swing.JTextField();
        doubleClearBUT = new javax.swing.JButton();
        intAddBUT = new javax.swing.JButton();
        doubleAddBUT = new javax.swing.JButton();
        intSubBUT = new javax.swing.JButton();
        doubleSubBUT = new javax.swing.JButton();
        intMulBUT = new javax.swing.JButton();
        doubleMulBUT = new javax.swing.JButton();
        intDivBUT = new javax.swing.JButton();
        doubleDivBUT = new javax.swing.JButton();
        intModBUT = new javax.swing.JButton();
        intPowBUT = new javax.swing.JButton();
        doublePowBUT = new javax.swing.JButton();
        intClearBUT = new javax.swing.JButton();
        warningLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        deltaIntLBL.setText("Delta Integer");
        getContentPane().add(deltaIntLBL);
        deltaIntLBL.setBounds(50, 120, 110, 30);

        intLBL.setText("Integer");
        getContentPane().add(intLBL);
        intLBL.setBounds(50, 40, 40, 20);

        doubleLBL.setText("Double");
        getContentPane().add(doubleLBL);
        doubleLBL.setBounds(240, 40, 40, 20);

        deltaDoubleLBL.setText("Delta-Double");
        getContentPane().add(deltaDoubleLBL);
        deltaDoubleLBL.setBounds(240, 120, 120, 30);

        deltaDoubleTF.setText("0.0");
        deltaDoubleTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deltaDoubleTFActionPerformed(evt);
            }
        });
        getContentPane().add(deltaDoubleTF);
        deltaDoubleTF.setBounds(240, 160, 130, 20);

        intTF.setText("0");
        intTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intTFActionPerformed(evt);
            }
        });
        getContentPane().add(intTF);
        intTF.setBounds(50, 80, 130, 20);

        doubleTF.setText("0.0");
        doubleTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleTFActionPerformed(evt);
            }
        });
        getContentPane().add(doubleTF);
        doubleTF.setBounds(240, 80, 130, 20);

        deltaIntTF.setText("0");
        deltaIntTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deltaIntTFActionPerformed(evt);
            }
        });
        getContentPane().add(deltaIntTF);
        deltaIntTF.setBounds(50, 160, 130, 20);

        doubleClearBUT.setText("Clear");
        doubleClearBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleClearBUTActionPerformed(evt);
            }
        });
        getContentPane().add(doubleClearBUT);
        doubleClearBUT.setBounds(260, 380, 80, 23);

        intAddBUT.setText("+=");
        intAddBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intAddBUTActionPerformed(evt);
            }
        });
        getContentPane().add(intAddBUT);
        intAddBUT.setBounds(80, 200, 60, 23);

        doubleAddBUT.setText("+=");
        doubleAddBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleAddBUTActionPerformed(evt);
            }
        });
        getContentPane().add(doubleAddBUT);
        doubleAddBUT.setBounds(270, 200, 60, 23);

        intSubBUT.setText("-=");
        intSubBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intSubBUTActionPerformed(evt);
            }
        });
        getContentPane().add(intSubBUT);
        intSubBUT.setBounds(80, 230, 60, 23);

        doubleSubBUT.setText("-=");
        doubleSubBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleSubBUTActionPerformed(evt);
            }
        });
        getContentPane().add(doubleSubBUT);
        doubleSubBUT.setBounds(270, 230, 60, 23);

        intMulBUT.setText("*=");
        intMulBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intMulBUTActionPerformed(evt);
            }
        });
        getContentPane().add(intMulBUT);
        intMulBUT.setBounds(80, 260, 60, 23);

        doubleMulBUT.setText("*=");
        doubleMulBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleMulBUTActionPerformed(evt);
            }
        });
        getContentPane().add(doubleMulBUT);
        doubleMulBUT.setBounds(270, 260, 60, 23);

        intDivBUT.setText("/=");
        intDivBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intDivBUTActionPerformed(evt);
            }
        });
        getContentPane().add(intDivBUT);
        intDivBUT.setBounds(80, 290, 60, 23);

        doubleDivBUT.setText("/=");
        doubleDivBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleDivBUTActionPerformed(evt);
            }
        });
        getContentPane().add(doubleDivBUT);
        doubleDivBUT.setBounds(270, 290, 60, 23);

        intModBUT.setText("%=");
        intModBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intModBUTActionPerformed(evt);
            }
        });
        getContentPane().add(intModBUT);
        intModBUT.setBounds(80, 320, 60, 23);

        intPowBUT.setText("Raise to Power");
        intPowBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intPowBUTActionPerformed(evt);
            }
        });
        getContentPane().add(intPowBUT);
        intPowBUT.setBounds(40, 350, 140, 23);

        doublePowBUT.setText("Raise to Power");
        doublePowBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doublePowBUTActionPerformed(evt);
            }
        });
        getContentPane().add(doublePowBUT);
        doublePowBUT.setBounds(230, 350, 140, 23);

        intClearBUT.setText("Clear");
        intClearBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intClearBUTActionPerformed(evt);
            }
        });
        getContentPane().add(intClearBUT);
        intClearBUT.setBounds(70, 380, 80, 23);
        getContentPane().add(warningLBL);
        warningLBL.setBounds(60, 10, 290, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int integer = 0, deltaInteger = 0;  //creates values of each text field
    double decimal = 0, deltaDecimal = 0;

    private void intTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intTFActionPerformed
        //when the text field is used the value typed in is assigned to the variable integer
        integer = Integer.parseInt(intTF.getText());    //when typed, assigned to correct 
        warningLBL.setText("");
    }//GEN-LAST:event_intTFActionPerformed

    private void doubleClearBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleClearBUTActionPerformed
        //sets the values of the text fields to an empty string when the clear button is pressed
        warningLBL.setText("");
        doubleTF.setText("0.0");
        deltaDoubleTF.setText("0.0");
    }//GEN-LAST:event_doubleClearBUTActionPerformed

    private void intAddBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intAddBUTActionPerformed
        warningLBL.setText("");
        integer = Integer.parseInt(intTF.getText());    //when typed, assigned to correct 
        deltaInteger = Integer.parseInt(deltaIntTF.getText());
        integer += deltaInteger;
        intTF.setText(Integer.toString(integer));
    }//GEN-LAST:event_intAddBUTActionPerformed

    private void doubleAddBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleAddBUTActionPerformed
        warningLBL.setText("");
        decimal = Double.parseDouble(doubleTF.getText());
        deltaDecimal = Double.parseDouble(deltaDoubleTF.getText());
        decimal += deltaDecimal;
        doubleTF.setText(Double.toString(decimal));
    }//GEN-LAST:event_doubleAddBUTActionPerformed

    private void intSubBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intSubBUTActionPerformed
        warningLBL.setText("");
        integer = Integer.parseInt(intTF.getText());    //when typed, assigned to correct 
        deltaInteger = Integer.parseInt(deltaIntTF.getText());
        integer -= deltaInteger;
        intTF.setText(Integer.toString(integer));
    }//GEN-LAST:event_intSubBUTActionPerformed

    private void doubleSubBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleSubBUTActionPerformed
        warningLBL.setText("");
        decimal = Double.parseDouble(doubleTF.getText());
        deltaDecimal = Double.parseDouble(deltaDoubleTF.getText());
        decimal -= deltaDecimal;
        doubleTF.setText(Double.toString(decimal));
    }//GEN-LAST:event_doubleSubBUTActionPerformed

    private void intMulBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intMulBUTActionPerformed
        warningLBL.setText("");
        integer = Integer.parseInt(intTF.getText());    //when typed, assigned to correct 
        deltaInteger = Integer.parseInt(deltaIntTF.getText());
        integer *= deltaInteger;
        intTF.setText(Integer.toString(integer));
    }//GEN-LAST:event_intMulBUTActionPerformed

    private void doubleMulBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleMulBUTActionPerformed
        warningLBL.setText("");
        decimal = Double.parseDouble(doubleTF.getText());
        deltaDecimal = Double.parseDouble(deltaDoubleTF.getText());
        decimal *= deltaDecimal;
        doubleTF.setText(Double.toString(decimal));

    }//GEN-LAST:event_doubleMulBUTActionPerformed

    private void intDivBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intDivBUTActionPerformed
        warningLBL.setText("");
        integer = Integer.parseInt(intTF.getText());    //when typed, assigned to correct 
        deltaInteger = Integer.parseInt(deltaIntTF.getText());
        if (zeroHandled(true)) {
            integer /= deltaInteger;
            intTF.setText(Integer.toString(integer));
        } else {
            warningLBL.setText("You cannot divide by zero.");
        }
    }//GEN-LAST:event_intDivBUTActionPerformed

    private void doubleDivBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleDivBUTActionPerformed
        warningLBL.setText("");
        decimal = Double.parseDouble(doubleTF.getText());
        deltaDecimal = Double.parseDouble(deltaDoubleTF.getText());
        if (zeroHandled(false)) {    //if you are not diving by zero
            decimal /= deltaDecimal;
            doubleTF.setText(Double.toString(decimal));
        } else {    //warns the user they are trying to divide by zero
            warningLBL.setText("You cannot divide by zero.");
        }

    }//GEN-LAST:event_doubleDivBUTActionPerformed

    private void intModBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intModBUTActionPerformed
        warningLBL.setText("");
        integer = Integer.parseInt(intTF.getText());    //when typed, assigned to correct 
        deltaInteger = Integer.parseInt(deltaIntTF.getText());
        if (zeroHandled(true)) {    //if you are not diving by zero
            integer %= deltaInteger;
            intTF.setText(Integer.toString(integer));
        } else {    //warns the user they are trying to divide by zero
            warningLBL.setText("You cannot divide by zero.");
        }
    }//GEN-LAST:event_intModBUTActionPerformed

    private void intPowBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intPowBUTActionPerformed
        warningLBL.setText("");
        integer = Integer.parseInt(intTF.getText());    //when typed, assigned to correct 
        deltaInteger = Integer.parseInt(deltaIntTF.getText());
        integer = (int) Math.pow(integer, deltaInteger);
        intTF.setText(Integer.toString(integer));
    }//GEN-LAST:event_intPowBUTActionPerformed

    private void doublePowBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doublePowBUTActionPerformed
        warningLBL.setText("");
        decimal = Double.parseDouble(doubleTF.getText());
        deltaDecimal = Double.parseDouble(deltaDoubleTF.getText());
        decimal = Math.pow(decimal, deltaDecimal);
        doubleTF.setText(Double.toString(decimal));
    }//GEN-LAST:event_doublePowBUTActionPerformed

    private void intClearBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intClearBUTActionPerformed
        //sets the values of the text fields to an empty string when the clear button is pressed
        warningLBL.setText("");
        intTF.setText("0");
        deltaIntTF.setText("0");
    }//GEN-LAST:event_intClearBUTActionPerformed

    private void deltaIntTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deltaIntTFActionPerformed
        //when the text field is used the value typed in is assigned to the variable integer
        warningLBL.setText("");
        deltaInteger = Integer.parseInt(intTF.getText());
    }//GEN-LAST:event_deltaIntTFActionPerformed

    private void doubleTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleTFActionPerformed
        warningLBL.setText("");
        decimal = Integer.parseInt(intTF.getText());
    }//GEN-LAST:event_doubleTFActionPerformed

    private void deltaDoubleTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deltaDoubleTFActionPerformed
        warningLBL.setText("");
        deltaDecimal = Integer.parseInt(intTF.getText());
    }//GEN-LAST:event_deltaDoubleTFActionPerformed

    public boolean zeroHandled(boolean isInt) {  //checks whether or not you are doing an operation by zero that cannot be completed (int mod, dividing)
        if (isInt) {
            if (deltaInteger == 0) {
                return false;
            } else {
                return true;
            }
        } else {
            if (deltaDecimal == 0) {
                return false;
            } else {
                return true;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deltaDoubleLBL;
    private javax.swing.JTextField deltaDoubleTF;
    private javax.swing.JLabel deltaIntLBL;
    private javax.swing.JTextField deltaIntTF;
    private javax.swing.JButton doubleAddBUT;
    private javax.swing.JButton doubleClearBUT;
    private javax.swing.JButton doubleDivBUT;
    private javax.swing.JLabel doubleLBL;
    private javax.swing.JButton doubleMulBUT;
    private javax.swing.JButton doublePowBUT;
    private javax.swing.JButton doubleSubBUT;
    private javax.swing.JTextField doubleTF;
    private javax.swing.JButton intAddBUT;
    private javax.swing.JButton intClearBUT;
    private javax.swing.JButton intDivBUT;
    private javax.swing.JLabel intLBL;
    private javax.swing.JButton intModBUT;
    private javax.swing.JButton intMulBUT;
    private javax.swing.JButton intPowBUT;
    private javax.swing.JButton intSubBUT;
    private javax.swing.JTextField intTF;
    private javax.swing.JLabel warningLBL;
    // End of variables declaration//GEN-END:variables
}
