
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author walksydn
 */
public class PNZFrame extends javax.swing.JFrame {

    /**
     * Creates new form PNZFrame
     */
    public PNZFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guessTF = new javax.swing.JTextField();
        guessBUT = new javax.swing.JButton();
        tableTA = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        newGameBUT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        guessTF.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        guessTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessTFActionPerformed(evt);
            }
        });
        getContentPane().add(guessTF);
        guessTF.setBounds(70, 50, 80, 30);

        guessBUT.setText("Guess!");
        guessBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessBUTActionPerformed(evt);
            }
        });
        getContentPane().add(guessBUT);
        guessBUT.setBounds(240, 50, 80, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        tableTA.setViewportView(jTextArea1);

        getContentPane().add(tableTA);
        tableTA.setBounds(110, 110, 170, 210);

        newGameBUT.setText("New Game");
        newGameBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameBUTActionPerformed(evt);
            }
        });
        getContentPane().add(newGameBUT);
        newGameBUT.setBounds(140, 340, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String guess = "";
    String answer = "", output = "";
    Random random = new Random();
    private void guessTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessTFActionPerformed
        
    }//GEN-LAST:event_guessTFActionPerformed

    private void guessBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessBUTActionPerformed
        guess = guessTF.getText();
        
    }//GEN-LAST:event_guessBUTActionPerformed

    private void newGameBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameBUTActionPerformed
        startNewGame();
        output = evaluateGuess(answer, guess);
        displayResults(guess, output);
    }//GEN-LAST:event_newGameBUTActionPerformed

    
    public void startNewGame(){
        
    }
    
    public char randomDigit(){
        return (char)(random.nextInt(9) + 1);
    }
    
    public String randomString(){
        answer = Integer.toString(randomDigit()) + Integer.toString(randomDigit()) + Integer.toString(randomDigit());
        return answer;
    }
    
    public String evaluateGuess(String target, String result){
        
    }
    
    public void displayResults(String guess, String result){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guessBUT;
    private javax.swing.JTextField guessTF;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton newGameBUT;
    private javax.swing.JScrollPane tableTA;
    // End of variables declaration//GEN-END:variables
}
