/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chris
 */
public class AboutFrame extends javax.swing.JFrame {

    /**
     * Creates new form AboutFrame
     */
    public AboutFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictLBL = new javax.swing.JLabel();
        dlgLBL = new javax.swing.JLabel();
        guessLBL = new javax.swing.JLabel();
        closeBUT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));
        getContentPane().setLayout(null);

        pictLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2011.JPG"))); // NOI18N
        getContentPane().add(pictLBL);
        pictLBL.setBounds(70, 50, 703, 387);

        dlgLBL.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        dlgLBL.setForeground(new java.awt.Color(204, 0, 0));
        dlgLBL.setText("Class of 2011 APCS - Sample by mr Hanley");
        getContentPane().add(dlgLBL);
        dlgLBL.setBounds(140, 10, 520, 30);

        guessLBL.setFont(new java.awt.Font("Arial Unicode MS", 1, 24)); // NOI18N
        guessLBL.setForeground(new java.awt.Color(204, 0, 0));
        guessLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guessLBL.setText("Can you interpret the message???");
        getContentPane().add(guessLBL);
        guessLBL.setBounds(80, 450, 700, 30);

        closeBUT.setBackground(new java.awt.Color(255, 255, 51));
        closeBUT.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        closeBUT.setText("Close");
        closeBUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBUTActionPerformed(evt);
            }
        });
        getContentPane().add(closeBUT);
        closeBUT.setBounds(340, 510, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBUTActionPerformed
       this.dispose();
    }//GEN-LAST:event_closeBUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBUT;
    private javax.swing.JLabel dlgLBL;
    private javax.swing.JLabel guessLBL;
    private javax.swing.JLabel pictLBL;
    // End of variables declaration//GEN-END:variables
}
